from typing import Protocol
from pac_common.models import BoxState, PlacementCandidate, SystemState, ValidationResult
class CandidateGenerator(Protocol):
    def generate_candidates(self, box: BoxState, state: SystemState) -> list[PlacementCandidate]: ...
class ConstraintValidator(Protocol):
    def validate_constraints(self, box: BoxState, candidate: PlacementCandidate, state: SystemState) -> ValidationResult: ...
class CandidateEvaluator(Protocol):
    def evaluate_candidate(self, box: BoxState, candidate: PlacementCandidate, state: SystemState) -> PlacementCandidate: ...
class LookAheadEvaluator(Protocol):
    def evaluate_future_value(self, box: BoxState, candidate: PlacementCandidate, state: SystemState, seed: int) -> float: ...
