"""HDR50-22 forward / inverse kinematics for the Gazebo workcell (numpy only).

Chain constants are copied from the official hdr50_22 URDF generated by
pac_bringup/urdf/hdr50_pedestal.urdf.xacro (world_joint z=0.40 pedestal).
Target frame is ``flange_link``; its +x axis is the tool direction and the
flange face is at the frame origin.
"""
from __future__ import annotations

import math
from typing import Optional, Sequence

import numpy as np

BASE_Z_M = 0.40
# (xyz, rpy, axis) for j1..j6, parent -> child
JOINTS = (
    ((0.0, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, 0.0, 1.0)),
    ((0.32, 0.0, 0.48), (0.0, 1.5708, 0.0), (0.0, -1.0, 0.0)),
    ((0.0, 0.0, 0.87), (0.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
    ((0.0, 0.0, 0.2), (0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),
    ((1.03, 0.0, 0.0), (0.0, 0.0, 0.0), (0.0, -1.0, 0.0)),
    ((0.185, 0.0, 0.0), (0.0, 0.0, 0.0), (1.0, 0.0, 0.0)),
)
LOWER = np.array([-3.142, -1.134, -1.396, -6.283, -2.182, -6.283])
UPPER = np.array([3.142, 2.967, 3.141, 6.283, 2.182, 6.283])
VEL_LIMIT = np.array([3.054, 3.054, 3.054, 4.363, 4.363, 6.109])
HOME = np.array([0.0, 1.5707, 0.0, 0.0, 0.0, 0.0])  # hdr50_22 initial_positions.yaml


def _rpy(r: float, p: float, y: float) -> np.ndarray:
    cr, sr, cp, sp, cy, sy = math.cos(r), math.sin(r), math.cos(p), math.sin(p), math.cos(y), math.sin(y)
    return np.array([
        [cy * cp, cy * sp * sr - sy * cr, cy * sp * cr + sy * sr],
        [sy * cp, sy * sp * sr + cy * cr, sy * sp * cr - cy * sr],
        [-sp, cp * sr, cp * cr],
    ])


def _axis_angle(axis: Sequence[float], q: float) -> np.ndarray:
    x, y, z = axis
    c, s, v = math.cos(q), math.sin(q), 1.0 - math.cos(q)
    return np.array([
        [x * x * v + c, x * y * v - z * s, x * z * v + y * s],
        [y * x * v + z * s, y * y * v + c, y * z * v - x * s],
        [z * x * v - y * s, z * y * v + x * s, z * z * v + c],
    ])


def fk(q: Sequence[float], return_frames: bool = False):
    """World pose of flange_link as (p[3], R[3x3])."""
    p = np.array([0.0, 0.0, BASE_Z_M])
    R = np.eye(3)
    frames = []
    for (xyz, rpy, axis), qi in zip(JOINTS, q):
        p = p + R @ np.array(xyz)
        R = R @ _rpy(*rpy)
        frames.append((p.copy(), R @ np.array(axis)))
        R = R @ _axis_angle(axis, qi)
    return (p, R, frames) if return_frames else (p, R)


def tool_down_rotation(yaw: float = 0.0) -> np.ndarray:
    """Flange +x pointing down; flange +y along world yaw (box stays level)."""
    x = np.array([0.0, 0.0, -1.0])
    y = np.array([math.cos(yaw), math.sin(yaw), 0.0])
    return np.column_stack([x, y, np.cross(x, y)])


def _rot_error(R: np.ndarray, R_target: np.ndarray) -> np.ndarray:
    """Axis-angle (world frame) rotating R onto R_target; exact also near 180 deg."""
    E = R_target @ R.T
    c = max(-1.0, min(1.0, (np.trace(E) - 1.0) / 2.0))
    angle = math.acos(c)
    v = np.array([E[2, 1] - E[1, 2], E[0, 2] - E[2, 0], E[1, 0] - E[0, 1]])
    if angle < 1e-6:
        return 0.5 * v
    if angle < math.pi - 1e-3:
        return v * (angle / (2.0 * math.sin(angle)))
    # Near 180 deg: axis from the symmetric part.
    axis = np.sqrt(np.maximum((np.diag(E) + 1.0) / 2.0, 0.0))
    i = int(np.argmax(axis))
    axis = (E[:, i] + E[i, :]) / (2.0 * max(axis[i], 1e-9) * 2.0) if axis[i] > 0 else axis
    axis = axis / max(np.linalg.norm(axis), 1e-9)
    return axis * angle


def ik(p_target: Sequence[float], R_target: np.ndarray, seed: Sequence[float],
       tol_m: float = 1e-4, tol_rad: float = 1e-3, iters: int = 300) -> Optional[np.ndarray]:
    """Damped least-squares IK; returns joint vector within limits or None."""
    q = np.clip(np.array(seed, dtype=float), LOWER, UPPER)
    p_t = np.array(p_target, dtype=float)
    lam = 0.05
    for _ in range(iters):
        p, R, frames = fk(q, return_frames=True)
        e = np.concatenate([p_t - p, _rot_error(R, R_target)])
        if np.linalg.norm(e[:3]) < tol_m and np.linalg.norm(e[3:]) < tol_rad:
            return q
        J = np.zeros((6, 6))
        for i, (pi, zi) in enumerate(frames):
            J[:3, i] = np.cross(zi, p - pi)
            J[3:, i] = zi
        dq = J.T @ np.linalg.solve(J @ J.T + lam * lam * np.eye(6), e)
        q = np.clip(q + dq, LOWER, UPPER)
    return None


def ik_near(p_target, R_target, seeds) -> Optional[np.ndarray]:
    """Try seeds in order; return the first solution (closest to first seed preferred)."""
    best = None
    for s in seeds:
        sol = ik(p_target, R_target, s)
        if sol is not None:
            if best is None or np.abs(sol - seeds[0]).max() < np.abs(best - seeds[0]).max():
                best = sol
            if np.abs(sol - seeds[0]).max() < 1.0:
                return sol
    return best


def cartesian_path(q_start, p_end, R_target, step_m: float = 0.02):
    """Straight-line flange path from FK(q_start) to p_end; joint waypoints or None."""
    p0, _ = fk(q_start)
    p_end = np.array(p_end, dtype=float)
    n = max(1, int(math.ceil(np.linalg.norm(p_end - p0) / step_m)))
    q = np.array(q_start, dtype=float)
    out = []
    for k in range(1, n + 1):
        sol = ik(p0 + (p_end - p0) * k / n, R_target, q)
        if sol is None or np.abs(sol - q).max() > 0.35:  # reject branch flips
            return None
        out.append(sol)
        q = sol
    return out
